language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
services:
  - redis-server
env:
  - FLASK_ENV=dev
before_install: cd src/backend
install:
  - pip install pipenv
  - pipenv install
script:
  - nohup python manage.py runserver &
  - pytest test  -sv