language: python
python:
  - '3.7'
services:
  - redis-server
env:
  - FLASK_ENV=dev
jobs:
  include:
    - stage: deploy
      before_install: cd src/backend
      install:
        - pip install pipenv
        - pipenv install
      script:
        - nohup python manage.py runserver &
    - stage: test
      before_install: cd src/backend/test
      script: pytest 