language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
services:
  - redis-server
  - mysql
env:
  - FLASK_ENV=dev DB_PASSWORD=
before_install:
  - mysql -u root  < backend/mysql/docker-entrypoint-initdb.d/01_create_db.sql
  - mysql -u root  < backend/mysql/docker-entrypoint-initdb.d/02_table_structure.sql
  - cd backend/src
install:
  - pip install -r requirements.txt
script:
  - nohup python manage.py runserver &
  - pytest test  -sv