version: "3.7"

services:
  # MySQL Container
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Shanghai
    volumes:
      - ${BASE_DIR}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always

  # Redis Container
  redis:
    image: redis:5.0.5
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${BASE_DIR}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    restart: always

  # Flask App Container
  flask_app:
    build:
      context: ./src
    environment:
      - TZ=Asia/Shanghai
      - FLASK_ENV=${FLASK_ENV}
      - REDIS_HOST=${REDIS_HOST}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${BASE_DIR}/../src:/data/src
    depends_on:
      - redis
      - mysql
    command: bash -c "/data/src/scripts/wait-for-it.sh mysql:3306 && /data/src/scripts/run.sh "
    ports:
      - "${FLASK_PORT}:5000"
    restart: always
